### ISSUE TITLE
插件duplicate-style缺少配置项取消log输出

### ISSUE THREAD

**Issue by SeanLeeCai** [airyland/vux-loader#10]
我使用duplicate-style插件，每次都会输出
======== vux-loader: duplicate-style start~  ========
======== vux-loader: duplicate-style done!   ========

当有多个css时便会输出多次，能不能修改为默认不输出，至少给个配置项取消输出？

**Comment by airyland** [comment]
upgrade to 1.0.48.
Now log is disabled by default and can be enabled by:

``` js
{
      name: 'duplicate-style',
      options: {
        canPrint: true
      }
}
```

**Comment by distance295** [comment]
Now log is disabled at 1.2.2. This option also can not work.
