### ISSUE TITLE
升级了一下版本，build时无反应

### ISSUE THREAD

**Issue by agileago** [airyland/vux-loader#12]
我之前用的是 1.0.44版本， build项目时没问题，也很快，升级到了 1.0.54，再build就不行了，webpack打包完就停在那里一动不动了

具体复现步骤

```bash
$ vue init agileago/webpack-mutiple test
$ cd test
$ yarn
$ yarn run vendor
$ yarn run dev
$ yarn run build
```
模板锁定了vux-loader的版本是1.0.44，所以一切没问题，但假如说升级一下版本就不能build了

```bash
$ yarn remove vux-loader
$ yarn add vux-loader
$ yarn run build
```

也不报错，就停在那里不动了

**Comment by airyland** [comment]
构建时代码里
或者命令行设置
cross-env NODE_ENV=production

**Comment by agileago** [comment]
![image](https://cloud.githubusercontent.com/assets/11799110/23931369/c92f196c-096c-11e7-81f4-fdfced8b3def.png)
这个不行么？

**Comment by airyland** [comment]
不行啊。。这是webpack内部使用的，跟进程无关系。你比官方模板少了个 build.js，所以缺少了环境设置。

**Comment by agileago** [comment]
好吧！我试试，谢谢

**Comment by agileago** [comment]
试了一下，ok了，但现在是没有提示了么？说构建前css多少构建后去除了多少？没感觉到底执行了没有

**Comment by airyland** [comment]
这个之前有用户说看着比较烦，所以默认去掉了。下一版本在 production 下默认显示。

**Comment by airyland** [comment]
v1.0.56 已发。
