### ISSUE TITLE
有没有配合cookingjs的列子

### ISSUE THREAD

**Issue by lileltp** [airyland/vux-loader#13]
开始项目为了简单配置webpack.使用了cookingjs.
`const webpackConfig = cooking.resolve()`
`module.exports = webpackConfig`
`const vuxLoader = require('vux-loader')`
`module.exports = vuxLoader.merge(webpackConfig, {`
`  options: {},`
`  plugins: [{`
`   name: 'vux-ui'`
`  }]`
`})`
理论cooking.resolve()返回的也是webpack配置.但是这样使用后vue也失效了.
实在不清楚怎么弄.但还是想使用vux.所以只能发到这里问问.

**Comment by airyland** [comment]
没用过。暂时没时间去折腾，并且 cookingjs 似乎也不是非常流行的样子。。
如果你是新项目直接重新用模板创建咯。

**Comment by lileltp** [comment]
好吧
