### ISSUE TITLE
template or render function not defined

### ISSUE THREAD

**Issue by ds-aco** [airyland/vux-loader#16]
我没有用官方的vue-cli,而是安装了vux-loader
![t snt ay2l7pho4flg](https://cloud.githubusercontent.com/assets/12523637/26518109/77b96738-42db-11e7-92d6-8ececd72184d.png)
config如上图所示 
直接导出webpackConfig,可以正常运行,
但是导出config的话 就会有如标题所示的错误

**Comment by airyland** [comment]
比较奇怪，细节不足以重现，麻烦建个 repo。
