### ISSUE TITLE
vux-loader @1.0.68 自定义reset.css 无效

### ISSUE THREAD

**Issue by jiangchengshi** [airyland/vux-loader#18]
vux-loader @1.0.68 自定义reset.css 在 主App.vue中引用，样式 无效。

  /* 引入Reset样式*/
    @import "../css/reset.css";

1.0.63 可以正常使用

**Comment by airyland** [comment]
不要在不同 repo 开 issue。并且已经回复你，vux-loader 不会处理样式文件。
如果有问题，上 repo 来看看。
