### ISSUE TITLE
vue-loader升级到了13.0.0导致vux-loader配置出错

### ISSUE THREAD

**Issue by FioneraGH** [airyland/vux-loader#21]
hi，vue-loader升级到13.0.0，打包时没办法按需打包了，打包时间也很久，会看到vux-loader的提示。

看vue-loader 13.0.0的changelog使用了es方式处理模块，暂时可以把esModule置为false解决这个问题，vux-loader何时可以适配。

非常感谢开发者的支持。

**Comment by airyland** [comment]
升级到 vux-loader@1.1.0。
