### ISSUE TITLE
vux文档的vux-loader部分的章节，“开源组件多语言支持”疑惑

### ISSUE THREAD

**Issue by PetersonLian** [airyland/vux-loader#27]
该章节文档里头说到：
>开源组件多语言支持
>
>如果以js方式分发，一般默认一个语言，用户可以加上另外的语言包，但是代码里必不可少存在相应的转换函数，对于只需要单语言的人来是个浪费和繁琐。要么所有一起打包，这个也极浪费。要么一个一个打包，这样又失去了动态多语言支持。
>
>于是vux在vux-loader的支持下实现了使用时构建，无论是静态输出和动态支持。

[[具体文档]](https://vux.li/#/zh-CN/vux-loader?id=%E5%BC%80%E6%BA%90%E7%BB%84%E4%BB%B6%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81)

对于`使用时构建`，想知道，具体的`vux-loader`源码的逻辑体现在哪里？

**Comment by airyland** [comment]
vux-loader 重写了 vue-loader 处理后的代码，在 vue-loader 的几个 loader 处理前注入了自定义逻辑先处理了 vux 的组件源码，因此可以方便地对代码进行预处理。

**Comment by PetersonLian** [comment]
@airyland thx .是指这个意思啊。
