### ISSUE TITLE
使用AjaxPlugin from 'vux'报错

### ISSUE THREAD

**Issue by tangyuanhaha** [airyland/vux-loader#28]
我是个刚学vue的，使用import { AjaxPlugin } from 'vux';就报
 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件
我的vux-loader版本是最新版了，我用import flexbox from 'vux/src/components/flexbox/flexbox';能正常使用，我单独使用axios是可以的，代码为：
import Vue from 'vue';
import flexbox from 'vux/src/components/flexbox/flexbox';
import { AjaxPlugin } from 'vux';
import App from './App';
import router from './router';
Vue.use(flexbox);
console.log(flexbox);
Vue.use(AjaxPlugin);
控制台打印出来是：
VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
main.js?67d2:10 Object {name: "flexbox", props: Object, computed: Object, staticRenderFns: Array[0], __file: "G:\hebaodai\node_modules\vux\src\components\flexbox\flexbox.vue"…}_Ctor: Object__file: "G:\hebaodai\node_modules\vux\src\components\flexbox\flexbox.vue"beforeCreate: Array[1]beforeDestroy: Array[1]computed: Objectname: "flexbox"props: Objectrender: ()staticRenderFns: Array[0]__proto__: Object
index.vue?aa2d:85ReferenceError: AjaxPlugin is not defined(…)

**Comment by airyland** [comment]
请说明下 webpack 怎么配置，具体是有没有配置 vux-loader。

**Comment by tangyuanhaha** [comment]
vux-loader的配置按照官网介绍里的如下写的：
const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [{
    name: 'vux-ui'
  }]
})

**Comment by huang34** [comment]
![qq 20170824101046](https://user-images.githubusercontent.com/31273659/29646210-a6b17ab6-88b4-11e7-8d16-be0ecceb9cae.png)

**Comment by huang34** [comment]
![1](https://user-images.githubusercontent.com/31273659/29646363-a244d42c-88b5-11e7-9d55-b49cc46bd3c7.png)
![2](https://user-images.githubusercontent.com/31273659/29646365-a3626a4a-88b5-11e7-8e65-c90ff63d63a6.png)

**Comment by airyland** [comment]
@huang34 我请你不要在不同 issue 下发评论好吗。你直接用脚手架吧。你原来的配置呢，怎么可能是个空对象。

参照这里吧 https://github.com/airyland/vux2/blob/master/template/build/webpack.base.conf.js

**Comment by huang34** [comment]
@airyland 我发现您是个暴脾气。

**Comment by airyland** [comment]
@huang34 

Fuck you. 
我让你发文件给我是我对项目负责，可是你连配置没有按照文档来，我让你加配置你却要我帮你改。
你看不懂文档，怪我咯。也请你不要用 VUX，你不配。
你除了浪费别人时间还能花点时间反省吗？
