### ISSUE TITLE
$t is not defined

### ISSUE THREAD

**Issue by huang34** [airyland/vux-loader#29]
一：我之前是好好的，今天 升级一下，就报错。
二：我项目从没使用过$t，还是报错
三：我把vux-loader升级过了，还是报错
四：我也清除了node_modules使用npm install重新安装，还是报错
请问如何解决

**Comment by huang34** [comment]
期待您的回复。

**Comment by airyland** [comment]
不好判断，请提供一下调试窗口的 vux 版本提示。

![image](https://user-images.githubusercontent.com/559179/29607525-14a6dbb0-8824-11e7-9832-1e30b79d047c.png)

**Comment by huang34** [comment]
不知道 如何上传图片
  "dependencies": {
    "moment": "^2.18.1",
    "vue": "^2.3.3",
    "vue-resource": "^1.3.4",
    "vue-router": "^2.6.0",
    "vuex": "^2.3.1",
    "vux": "^2.5.8",
    "vux-loader": "^1.1.5"
  }
vue.esm.js?65d7:479 [Vue warn]: Error in render function: "TypeError: _vm.$t is not a function"

**Comment by huang34** [comment]
@airyland     "webpack": "^2.6.1",
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "dependencies": {
    "moment": "^2.18.1",
    "vue": "^2.3.3",
    "vue-resource": "^1.3.4",
    "vue-router": "^2.6.0",
    "vuex": "^2.3.1",
    "vux": "^2.5.8",
    "vux-loader": "^1.1.5"
  },

**Comment by airyland** [comment]
话说，你都  AT 了谁啊。。

版本看起来没什么问题，打个包或者建个 repo 吧，这样可以很快找到问题。

**Comment by huang34** [comment]
@airyland  打包给您吗？

**Comment by airyland** [comment]
没有敏感的东西直接发我邮箱， i@mao.li

**Comment by airyland** [comment]
哎，你都没有配置 vux-loader 吧。

**Comment by huang34** [comment]
我有配置哇。之前都是好好的，正常运行，昨天一升级就坏了。
您可以看哇。

**Comment by airyland** [comment]
就是看过才觉得你提这问题是在浪费时间。我没找到你 webpack 哪个配置里有用 vux-loader 的 merge 方法。你真看过 vux 文档了？

**Comment by huang34** [comment]
我当然看了啊。看着头都大了。
关键的是为什么之前好好的，后面为何不行了。您要是觉得有问题。你直接给我改正说明了。
您的文档写的，一大堆，看着头都大。

**Comment by airyland** [comment]
抱歉，我不可能浪费时间给你改正说明。你没用到 vux-loader 却在 vux-loader 提 issue 这本身就是在浪费我时间了？
