### ISSUE TITLE
vuxLoader.merge 多次调用无效

### ISSUE THREAD

**Issue by evecalm** [airyland/vux-loader#3]
我使用 <https://github.com/airyland/vux2> (vux-loader version **1.0.24**)提供的模板编写应用，想在build时自动将组件改成异步组件。于是我在 `webpack.prod.conf.js` 末尾加入了以下代码

```js
webpackConfig = vuxLoader.merge(webpackConfig, {
  plugins: [{
    name: 'js-parser',
    test: /pages\/components\.js$/,
    fn(source) {
      source = source.replace(/^\s*import\s+(\w+)\s+from\s+([^;]+?);?\s*$/gm, ($0, $1, $2) => {
        return `const ${$1} = function (resolve) {
  require([${$2}], resolve)
}`
      })
      return source
    }
  }]
}
```

使用webpack build，组件会分片，但是分片文件内容一模一样且只有几行代码，项目无法正常运行。查阅 `vux-loader` 源码后通过以下代码解决了

```js
const merge = require('webpack-merge')
const vuxConfig = {...}
webpackConfig = merge(webpackConfig, { vux: vuxConfig }
```

项目比较着急，没有细看是什么原因。

**Comment by airyland** [comment]
这样用的话，貌似vux-loader就不起作用了啊。得确认下你替换后的代码是否是正确的。

**Comment by evecalm** [comment]
我现在就是这样用的，用后边的代码问题解决了。

**Comment by airyland** [comment]
如果没有用vux-loader的merge方法，不修改`vue-loader`为`vux-loader!vue-loader`是已经不会经过js-parser了。。

**Comment by evecalm** [comment]
<https://github.com/airyland/vux2> 中的 `webpack.base.conf.js` 已经使用了一次了。看了下 vux-loader 的 `src/index.js` 并未对 `js-parser` 做特殊处理

**Comment by airyland** [comment]
所以上面你的配置其实是第二次merge么。

**Comment by evecalm** [comment]
对呀，使用的 `webpack-merge`

**Comment by halaproliu** [comment]
我添加
`const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
  ]
})`
这个配置，直接报错unexpected token import，请问你有遇到吗？

**Comment by yuemeimei** [comment]
\wechat\wechat\node_modules\_vux-loader@1.1.1@vux-loader\src\index.js:341
      const hasVueLoader = rule.use && rule.use.length && rule.use.filter(function(one) {
                                                                   ^

TypeError: rule.use.filter is not a function
    at D:\wechat\wechat\node_modules\_vux-loader@1.1.1@vux-loader\src\index.js:341:68
    at Array.forEach (native)
    at Function.module.exports.merge (D:\wechat\wechat\node_modules\_vux-loader@1.1.1@vux-loader\src\index.js:340:30)
    at Object.<anonymous> (D:\wechat\wechat\build\webpack.base.conf.js:95:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
我的一直报这个错

**Comment by airyland** [comment]
@yuemeimei 连配置都不帖就请自行解决吧。

**Comment by yuemeimei** [comment]
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var webpack = require("webpack")
var vueLoaderConfig = require('./vue-loader.conf')
var vuxLoader = require('vux-loader')
var merge = require('webpack-merge');
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

var webpackConfig = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
      '_config': resolve('config'),
      'jquery':'jquery'
    },

  },
  plugins: [
      new webpack.ProvidePlugin({
          $: "jquery",
          jQuery: "jquery"
      })
   ],
  module: {
    rules: [
      // {
      //   test: /\.(js|vue)$/,
      //   loader: 'eslint-loader',
      //   enforce: 'pre',
      //   include: [resolve('src'), resolve('test')],
      //   options: {
      //     formatter: require('eslint-friendly-formatter'),
      //     fix: true,
      //     emitError: true,
      //     emitWarning: true,
      //     failOnWarning: true,
      //     failOnError: true
      //   }
      // },
      {
        test: /\.json$/,
        use: 'json-loader'
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
       {
        test: /\.css$/,
        loaders: ['style-loader', 'css-loader'],
      }, {
        test: /\.scss$/,
        loaders: ['style', 'css', 'sass']
      },

    ]
  }
}


module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui']
})

**Comment by airyland** [comment]
@yuemeimei 

一般单个 loader 使用 `loader` 来配置，用 `use` 默认认为是数组。升级到 vux-loader@^1.1.2 或者直接改成 `loader: 'json-loader'`

``` js
{
test: /.json$/,
use: 'json-loader'
}
```

**Comment by yuemeimei** [comment]
@airyland 谢谢您，就是这个问题，已经解决了
