### ISSUE TITLE
style插入顺序

### ISSUE THREAD

**Issue by F-loat** [airyland/vux-loader#4]
```
    "vux-loader": "^1.0.24"
```
使用 `vue-cli` 工具和 `airyland/vux2` 模板初始化项目后，
直接在vue文件的style标签中添加样式无法覆盖同优先级默认样式，
原因是vue文件中的样式在import进的组件样式之前被插入，后插入的组件的默认样式覆盖了自定义的样式
``` vue
<template>
  <div>
    <div class="vux-demo">
      <img class="logo" src="../assets/vux_logo.png">
      <h1> </h1>
    </div>
    <group title="cell demo">
      <cell title="Vux" value="Cool" is-link></cell>
    </group>
  </div>
</template>

<script>
import { Group, Cell } from 'vux';

export default {
  components: {
    Group,
    Cell,
  },
  data() {
    return {
      // note: changing this line won't causes changes
      // with hot-reload because the reloaded component
      // preserves its current state and we are modifying
      // its initial state.
      msg: 'Hello World!',
    };
  },
};
</script>

<style>
.weui_cell_bd > p {
  color: red;
}
.vux-demo {
  text-align: center;
}
.logo {
  width: 100px;
  height: 100px
}
</style>
```
以上代码运行后字体颜色仍为默认的黑色

**Comment by airyland** [comment]
这个需要样式优先级来保证了，并不是vux-loader的问题。

**Comment by F-loat** [comment]
确实，只使用vue-loader也有一样的问题，其实只要保证ui库默认的样式在自定义样式之前插入，就可以实现同优先级也可以覆盖了，这方面没有什么办法可以优化吗

**Comment by airyland** [comment]
一般要自己加个类名来提高优先级，或者用important。

如果是script引入的形式先引入整体样式库，再引入自己样式倒是可以。

但是这里理论上还是可以通过工程化实现的，在vux-loader逻辑里，如果是组件库样式，抽取到一个文件，如果是项目样式抽取到另一个文件，就可以保证插入样式的先后顺序。

**Comment by F-loat** [comment]
嗯，感觉现在这种提高优先级的写法还是不是太好，一般在main.js里引用的组件，只要我把`import App from './app';`写在引用组件之后就可以了，但是在单个文件里引用的话就没办法了，同优先级的自定义样式总是会被覆盖，不太清楚vue-loader是怎么处理script中引用的样式和style中的样式的，可以的话还是希望后期可以优化下这方面
