### ISSUE TITLE
使用vux 打包平均450k

### ISSUE THREAD

**Issue by fooller** [airyland/vux-loader#40]
这个issues也许提的不应该！可实在没辙！
在项目中这么引入的，打包并且压缩后，出来就400k，不知道 是自己写法有问题 还是loadder有问题！
import {
  Group,
  Cell,
  Tabbar,
  TabbarItem,
  XTextarea,
  XTable,
  Divider
} from "vux";

**Comment by airyland** [comment]
请给出重现 repo 否则我也不知道什么问题。

**Comment by fooller** [comment]
抱歉 打扰您了 我们已经找到了问题 我同事在uitils里的fetch.js里边引入了element-ui，所以每个调用api的js文件都会变得莫名其妙的大！

感谢您的回复！，祝好！
