### ISSUE TITLE
我刚通过npm 装的vux-loader，为什么还报错要我更新？

### ISSUE THREAD

**Issue by CowInChrysalises** [airyland/vux-loader#41]
index.vue?a177:15 [VUX warn] 抱歉，clocker 组件需要升级 vux-loader 到最新版本才能正常使用
(anonymous) @ index.vue?a177:15
./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vux/src/components/clocker/index.vue @ app.js:1122
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ index.vue:1
./node_modules/vux/src/components/clocker/index.vue @ app.js:5094
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ index.js:38
./node_modules/vux/index.js @ app.js:4918
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ selector.js?type=script&index=0&bustCache!./src/components/HelloWorld.vue:1
./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/HelloWorld.vue @ app.js:1826
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ HelloWorld.vue:1
./src/components/HelloWorld.vue @ app.js:6635
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ index.js:3
./src/router/index.js @ app.js:6651
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ main.js:4
./src/main.js @ app.js:6643
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:6660
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
index.js?34fc:3 VUX: 如果你看到这一行，说明 vux-loader 配置有问题或者代码书写规范的原因导致无法解析成按需引入组件，会导致打包体积过大。请升级到最新版本 vux-loader，建议开启 eslint(standard)。
(anonymous) @ index.js?34fc:3
./node_modules/vux/index.js @ app.js:4918
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ selector.js?type=script&index=0&bustCache!./src/components/HelloWorld.vue:1
./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/HelloWorld.vue @ app.js:1826
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ HelloWorld.vue:1
./src/components/HelloWorld.vue @ app.js:6635
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ index.js:3
./src/router/index.js @ app.js:6651
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ main.js:4
./src/main.js @ app.js:6643
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:6660
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728
index.vue?6270:53 [VUX] 抱歉，当前组件[cell]要求更新依赖 vux-loader@latest

**Comment by airyland** [comment]
因为你根本就没有按照文档配置过 vux-loader。
