### ISSUE TITLE
vux-loader 在非  production 环境构建时，会每隔 1200 秒向 https://vux.li/vux-loader-anonymous-tracking.html 报告数据，导致 webpack 不会退出

### ISSUE THREAD

**Issue by hooraygith** [airyland/vux-loader#42]
有时候我们在部署到线上的时候，特意不设置 process.env.NODE_ENV 为 production，这样 Vue 更好调试，但 vux-loader 在这时候会导致 webpack 运行结束后不退出。

能不能提供一个单独的配置来关闭这个数据上报，而不是靠环境来判断。

将 process.env.NODE_ENV 和 vuxLoader 里的 env 设置为同一个非 production 值也可以实现，但这样略显繁琐。

相关代码：

```javascript
const buildEnvs = vuxConfig.options.buildEnvs || ['production']
if (buildEnvs.indexOf(process.env.NODE_ENV) !== -1) {
  process.env.__VUX_BUILD__ = true
} else {
  process.env.__VUX_BUILD__ = false
}

if (process.env.__VUX_BUILD__.toString() === 'false' && (process.env.NODE_ENV !== 'production' && !process.env.VUE_ENV && !/build\/build/.test(process.argv) && !/webpack\.prod/.test(process.argv))) {
  require('./libs/report')
}
```

**Comment by airyland** [comment]
试一下在 vux-loader 的设置里配置 

```
options: {
  buildEnvs: ['localbuild', 'production']
}
```

**Comment by hooraygith** [comment]
无效，没在源码里找到任何 localbuild 的代码。

需要设置 process.env.NODE_ENV 为 production 或者 process.env.NODE_ENV=xxx && buildEnvs: ['xxx']

**Comment by airyland** [comment]
localbuild 是指你本地的环境名字，上面只是个示例。

**Comment by hooraygith** [comment]
也就是说一定要给 process.env.NODE_ENV 设置一个值才能关掉这个，可有些项目是用 webpack.DefinePlugin 这个来设置环境的，process.env.NODE_ENV 不一定会设置值（比如 vue-cli 生成的项目），vux-loader 是对 vue-cli 的项目根据文件名作了特殊处理。

还是觉得要提供一个配置最合适

**Comment by airyland** [comment]
使用最新版本试试，在 build done 时会清除计时器。

**Comment by hooraygith** [comment]
现在好了，问题修复很快，谢谢
