### ISSUE TITLE
提示vux-loader配置问题,会导致打包过大,更新loader问题.

### ISSUE THREAD

**Issue by wangyujie1207** [airyland/vux-loader#45]
用 vue-cli 和模板 airyland/vux2 来初始化的项目,webpack.base.conf.js配置看了看也默认配置了,依赖全用的npm 自己也试着更新了vux 和vux-loader;
配置如下: "vux": "^2.7.5" ; "vux-loader": "^1.1.28",

module: {
    rules: [
      ...(config.dev.useEslint ? [{
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter'),
          emitWarning: !config.dev.showEslintErrorsInOverlay
        }
      }] : []),
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('media/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}

module.exports = vuxLoader.merge(webpackConfig, {
  plugins: ['vux-ui', 'progress-bar', 'duplicate-style']
})

**Comment by emondora** [comment]
同样的问题

**Comment by FioneraGH** [comment]
看vux下的issue,是vue-loader的问题,降级到13.3.0

**Comment by zhfish** [comment]
13.3.0同样会有问题, 我是按照wiki手动配置来的,如何测试下哪里出的问题?

**Comment by wangyujie1207** [comment]
默认配置就是13.3.0

**Comment by wcldyx** [comment]
我也是这个问题，以前webpack2老项目没问题， 现在新项目用的是vue-cli最新的是webpack3的就出问题了，打包文件很大，貌似把vux的所以的都打包进来了

**Comment by Prasinooo** [comment]
同样的问题， vue-loader改为@13.3.0后 解决了

**Comment by F-loat** [comment]
默认的配置是 `"vue-loader": "^13.3.0"`，所以会安装 `13.x.x` 的最新版，也就是 `13.6.0`，最新版目前还不支持，降级到 `13.5.1` 及更低的版本都可以

**Comment by wenjayliu** [comment]
## 修改文件 `package.json`  去掉 `^`
```js  
"vue-loader": "13.3.0",

```
![mark](http://p068w1sbg.bkt.clouddn.com/blog/171224/hLB97DgbED.png?imageslim)

## `build\webpack.base.conf.js`  

![mark](http://p068w1sbg.bkt.clouddn.com/blog/171224/65gf3KDH87.png?imageslim)  

### 暂时解决

**Comment by Jiiiiiin** [comment]
相同问题！
