### ISSUE TITLE
npm run lint 命令检查完毕不会退出 lint 进程

### ISSUE THREAD

**Issue by AlanWenhao** [airyland/vux-loader#48]
### 执行 `npm run lint` eslint 进程不退出
以下是package.json scripts：
> `"lint": "eslint --ext .js,.vue src",`

### 导致的问题：
- 执行 `npm run lint`, eslint 检查完 js 文件后进程卡死，不会检查 `.vue` 文件，其不自动退出进程让开发者不能区分 `正在检查？` or `检查完毕`
- 配置 pre-commit 执行 `npm run lint` 之后，由于 lint 进程卡死，导致无法 commit

### 定位代码，我的 “解决” 方式
https://github.com/airyland/vux-loader/blob/master/src/libs/report.js#L34-L45
- 45行 `1200000` 这个定时器直接导致了卡死，注释之后功能正常
- 注释第 45 行问题解决

### 我的问题
- 这里似乎发送了一个请求？
- 可以请教这些代码是干嘛的吗？

**Comment by airyland** [comment]
没明白的是，lint 应该只检查代码书写，为什么执行了 vux-loader 的逻辑？

**Comment by airyland** [comment]
这个是用以匿名统计 vux-loader 使用情况的日志接口。

**Comment by AlanWenhao** [comment]
其实遇到的根本问题是，执行 `npm run lint` ，lint之后进程不会结束

**Comment by airyland** [comment]
你确定你的 lint 命令只执行了代码书写检查？如果是 vux-loader 引起的，意味着你 lint 里执行了 vux-loader 或者引入了 webpack 配置，请给个简单可重现 repo。

**Comment by AlanWenhao** [comment]
## `vue init airyland/vux2 projectPath` 这样初始化的项目会有这个情况
```
~/alan ᐅ vue init airyland/vux2 test-lint

  A newer version of vue-cli is available.

  latest:    2.9.2
  installed: 2.9.1

? Project name test-lint
? Project description A Vue.js project
? Author AlanWenhao <alan.zhang@juwai.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Airbnb
? Setup unit tests No
? Setup e2e tests with Nightwatch? No

   vue-cli · Generated "test-lint".

   To get started:

     cd test-lint
     npm install
     npm run dev

   Documentation can be found at https://vuejs-templates.github.io/webpack
```

**Comment by AlanWenhao** [comment]
- 如果我们在 `src` 下新建了一个 test.js:
```
const a  = 1;
console.log(a);
```
- run `./node_modules/.bin/eslint src/test.js`
eslint 结束后进程正常退出。
- 但是 run `./node_modules/.bin/eslint src/main.js`，进程会卡死，
因为 `main.js` 中有 import ‘**.vue’
- 然后通过插件 `why-node-is-running` 定位到代码

**Comment by airyland** [comment]
并不能重现。main.js 也不可能有 vux-loader 的逻辑吧，难道你在 main.js 里引入了 vux-loader?

**Comment by AlanWenhao** [comment]
不能重现啊。。。奇怪了
我使用 `vue init airyland/vux2 projectPath` 初始化的新项目就会有这样的问题。同事的也一样

**Comment by airyland** [comment]
你直接建个版本库 push 到 Github  我看看。

**Comment by AlanWenhao** [comment]
好

**Comment by AlanWenhao** [comment]
git@github.com:AlanWenhao/Vux-lint-issue.git
另外一个issue
构建出来之后的 `.gitignore` 文件自带冲突

**Comment by ThiefTMBadBad** [comment]
我也是这种情况，我按照@AlanWenhao你的做法，确实可以了，但是我又试了其他的方法，也能解决这个问题
`'import/no-duplicates': 'off'`
在eslint中关闭这个规则，我的eslint校验就不会卡住了

**Comment by ahjsrhj** [comment]
碰到了同样的问题，npm run lint没有任何反应
```
$ npm run lint

> saas-h5@1.0.0 lint /Users/xxx/Works/saas-h5
> eslint --ext .js,.vue src

```

**Comment by ThiefTMBadBad** [comment]
> 碰到了同样的问题，npm run lint没有任何反应
> 
> ```
> $ npm run lint
> 
> > saas-h5@1.0.0 lint /Users/xxx/Works/saas-h5
> > eslint --ext .js,.vue src
> ```

我之前是一点点排查的，你可以试试检查单个文件，应该是有反应的，我遇见过好多次，不能自己完成lint，就是卡住，一直不能完成，应该是有些规则导致的，一点点排查，应该是能解决的
如果没有反应，看看是不是lint没有启动

**Comment by ahjsrhj** [comment]
@ThiefTMBadBad  感谢，应该是这条规则导致的
```
  // check if imports actually resolve
  settings: {
    'import/resolver': {
      webpack: {
        config: 'build/webpack.base.conf.js',
      },
    },
  },
```
注释之后一切正常， `'import/no-duplicates': 'off'` 这条规则没有加也是正常的
