### ISSUE TITLE
按官网文档升级出错

### ISSUE THREAD

**Issue by halaproliu** [airyland/vux-loader#5]
按官网升级了^2.1.0-rc.34版本，在webpack.base.conf.js中添加
`const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
  ]
}),`
然而报错，出现index.js?5e94:2 Uncaught SyntaxError: Unexpected token import,不知道该如何解决，求解

**Comment by airyland** [comment]
index.js 是什么文件？
