### ISSUE TITLE
能不能加个可以自定义 svg 文件位置的环境变量 ？或者别的什么方式

### ISSUE THREAD

**Issue by 285858315** [airyland/vux-loader#53]
现在的图标文件都放在 node_modules/vux/src/icons 下，有点别扭。

**Comment by airyland** [comment]
额，项目 icon 你就直接放项目下来引用，不需要用 vux 自带的 icons 吧。。

**Comment by 285858315** [comment]
是用 type 不指定路径么？

**Comment by airyland** [comment]
对于默认 x-icon，vux-loader 会根据 type 找到图标路径。

**Comment by 285858315** [comment]
![_20180312173027](https://user-images.githubusercontent.com/2813953/37275773-1292c3d0-261b-11e8-8e14-d0260f26f541.png)
好像不起作用。

**Comment by 285858315** [comment]
可以 了。

**Comment by 285858315** [comment]
多谢。

**Comment by xieyihao** [comment]
请问icon x-icon组件里的图标不够用，怎样引入自定义的svg呢？
issues、segmentfault未找到使用例子，文档是仅是一句描述，没能理解怎么使用.

>组件来自于 Ionicons(MIT)，你可以在网站上面看到所有的图标。 
>该组件无法在script引入的方式中使用，需要自行拷贝 svg 资源。
