### ISSUE TITLE
控制台不显示log

### ISSUE THREAD

**Issue by hfc-advance** [airyland/vux-loader#54]
使用vux-loader后，vue文件console.log打印不出日志了，js文件没有问题

**Comment by airyland** [comment]
vux-loader 没有这个神奇的去除 console 的功能。你给的信息也不足以重现，请给出 repo。

**Comment by 13916253446** [comment]
没有使用vux-loader的话，不报错，用了之后报“Failed to mount component: template or render function not defined”，但是我webpack配置
`resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      '@': utils.resolve("../src"),
      'vue': 'vue/dist/vue.esm.js'
    }
  }`
照理说不应该报这个错的，这是啥情况？

**Comment by 13916253446** [comment]
问题，同[https://github.com/airyland/vux-loader/issues/16](url)

**Comment by airyland** [comment]
如果是 template or render function 这个问题就应该在提出 issue 里就写明，而不是写无法 console，涉及到 webpack 配置问题一开始就应该给出完整可以重现的配置。
