### ISSUE TITLE
和vue-loader 15.x的冲突了

### ISSUE THREAD

**Issue by ldwqh0** [airyland/vux-loader#63]
和vue-loader 15.x的冲突了，
因为最近vue-loader进行了一次升级。
升级后报错了。

**Comment by tinymins** [comment]
同问题 我这里已经冲突快一个月了 😂  正在一步一步剥离组件做最坏打算

**Comment by ldwqh0** [comment]
@tinymins 不要捉急上4和vue-loader15嘛！

**Comment by Jiiiiiin** [comment]
很座机呀 😆  


- 升级小测试打包对比

升级之前:
![升级之前](https://ws2.sinaimg.cn/large/006tNc79gy1ftbiwkpxdgj317m0fcdi7.jpg)

升级之后:
![升级之后](https://ws1.sinaimg.cn/large/006tNc79gy1ftbip84ioqj31bq0rw0ua.jpg)

**Comment by ldwqh0** [comment]
@Jiiiiiin webpack4确实优化了很多东西

**Comment by Jiiiiiin** [comment]
@airyland 老大有没有着手解决这个事了？ 呵呵

**Comment by wxfqf** [comment]
要在webpack中加入const { VueLoaderPlugin } = require("vue-loader")，在plugins 中添加 new VueLoaderPlugin()

**Comment by airyland** [comment]
vux-loader 已经迁移到 vux 版本库里，并且发布为 @vux/loader，请参照这里 https://github.com/airyland/vux/issues/3430
