### ISSUE TITLE
[Feature Request] 🎈如何在@vue/cli 3.0下安装使用vux-loader呢

### ISSUE THREAD

**Issue by lvisei** [airyland/vux-loader#67]
### Existing Component
是

### Component Name
webpack

### Description
🎈如何在@vue/cli 3.0下生成的webpack环境，安装使用vux-loader呢

**Comment by Devancn** [comment]
问题 +1

**Comment by co-kevin** [comment]
可以用一下这个插件 [vue-cli-plugin-vux](https://github.com/hookszhang/vue-cli-plugin-vux)

```
$ vue add vux
```

**Comment by airyland** [comment]
vux-loader 已经迁移到 vux 版本库里，并且发布为 @vux/loader，请参照这里 https://github.com/airyland/vux/issues/3430
