### ISSUE TITLE
[Bug Report] vux-loader 与 vue-cli 3.0 的兼容问题

### ISSUE THREAD

**Issue by liuy666** [airyland/vux-loader#70]
### vux-loader version
1.2.9

### OS/Browsers version
win10 / chrome版本 69.0.3497.100（正式版本） （32 位）

### Vue version
2.5.17

### Code

```html
vux-loader 与 最新的 vue-cli 3.x 存在兼容问题，通过查资料发现vue-loader@14.2.2 能正常使用，请问 vux-loader目前版本 支持什么版本的 vue-load ，未来是否支持更新的版本，能否在文档上提示，谢谢
```

### Steps to reproduce
null

### What is Expected?
更好的解决版本兼容问题

### What is actually happening?
null

**Comment by fantasy525** [comment]
同样的问题，希望及早更新

**Comment by airyland** [comment]
vux-loader 已经迁移到 vux 版本库里，并且发布为 @vux/loader，请参照这里 https://github.com/airyland/vux/issues/3430
