### ISSUE TITLE
[Bug Report] 使用@vue/loader 2.0.0-rc3 图片不能正确显示

### ISSUE THREAD

**Issue by tyuan511** [airyland/vux-loader#80]
### vux-loader version
1.2.10-beta.1

### OS/Browsers version
macos 10.14.4

### Vue version
2.6.10

### Code

```html
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>
```

### Steps to reproduce
配置好@vux/loader之后运行项目，图片url正确，但是不显示

### What is Expected?
图片可以正常显示

### What is actually happening?
图片不能正常显示

**Comment by airyland** [comment]
升级到 rc4。
